project:
  type: website
  output-dir: _site

website:
  title: "Link Checker Reports"
  navbar:
    left:
      - text: "Process & Documentation"
        menu:
          - text: "Code and Process Description"
            href: 01_code_process.qmd
          - text: "Data Collection and Storage"
            href: 02_data_collection_storage.qmd
          - text: "Error Handling and Captured Data"
            href: 03_error_handling.qmd
          - text: "Recommendations and Librarian Guidance"
            href: 04_recomendations_librarians.qmd
      - text: "Reports"
        menu:
          # --- All Units header (non-clickable) ---
          - text: "All Units"
          - text: "2025-05-01 Link Checker Report (All Units)"
            href: Reports/All_Units/2025-05-01.ipynb
          # --- Individual Units header (non-clickable) ---
          - text: "Individual Units"
          - text: "2025-05-01, Link Checker Report for HEB"
            href: Reports/Individual_Units/2025-05-01_HEB.ipynb

format:
  html:
    inherit: default
    confluence:
      server: "https://yalelibrary.atlassian.net/"
      user: irma.fraticelli@yale.edu
      # space: "~712020f4e7f7ebdd074f61ab698475061add47"

execute:
  echo: false
  cache: true
